local Items = {}
Items.Water={Id="Water",Name="Water",Machine="CornerStore",Weight=1000000,Rarity="Common",BaseValue=5,BaseOneIn=2,AssetKey="WaterBottle",VisualFamily="Bottle",CosmeticSlot="Shoulder",Set="SodaSet",Color=Color3.fromRGB(118,196,255)}
Items.Cola={Id="Cola",Name="Cola",Machine="CornerStore",Weight=500000,Rarity="Common",BaseValue=8,BaseOneIn=4,AssetKey="BloxyColaMesh",VisualFamily="Can",CosmeticSlot="Head",Set="SodaSet",Color=Color3.fromRGB(214,66,66)}
Items.LemonSoda={Id="LemonSoda",Name="Lemon Soda",Machine="CornerStore",Weight=200000,Rarity="Uncommon",BaseValue=15,BaseOneIn=9,AssetKey="SodaCan",VisualFamily="Can",CosmeticSlot="Trail",Set="SodaSet",Color=Color3.fromRGB(247,226,80)}
Items.OrangeSoda={Id="OrangeSoda",Name="Orange Soda",Machine="CornerStore",Weight=75000,Rarity="Rare",BaseValue=35,BaseOneIn=24,AssetKey="SodaCanMesh",VisualFamily="Can",CosmeticSlot="Shoulder",Set="SodaSet",Color=Color3.fromRGB(255,149,53)}
Items.Chips={Id="Chips",Name="Chips",Machine="CornerStore",Weight=20000,Rarity="Epic",BaseValue=90,BaseOneIn=90,AssetKey="PotatoChips",VisualFamily="Bag",CosmeticSlot="Back",Set="SnackSet",Color=Color3.fromRGB(240,194,67)}
Items.Cookies={Id="Cookies",Name="Cookies",Machine="CornerStore",Weight=5000,Rarity="Legendary",BaseValue=250,BaseOneIn=360,AssetKey="CookieStack",VisualFamily="Box",CosmeticSlot="Head",Set="SnackSet",Color=Color3.fromRGB(183,125,80)}
Items.Chocolate={Id="Chocolate",Name="Chocolate",Machine="CornerStore",Weight=1000,Rarity="Mythic",BaseValue=800,BaseOneIn=1801,AssetKey="Chocolate",VisualFamily="Bar",CosmeticSlot="Shoulder",Set="SnackSet",Color=Color3.fromRGB(101,58,40)}
Items.Gummies={Id="Gummies",Name="Gummies",Machine="CornerStore",Weight=100,Rarity="Divine",BaseValue=5000,BaseOneIn=18011,AssetKey="GummyBears",VisualFamily="Bag",CosmeticSlot="Trail",Set="SnackSet",Color=Color3.fromRGB(255,91,137)}
Items.Pretzels={Id="Pretzels",Name="Pretzels",Machine="CornerStore",Weight=10,Rarity="Secret",BaseValue=50000,BaseOneIn=180111,AssetKey="ChipsPack",VisualFamily="Bag",CosmeticSlot="Back",Set="SnackSet",Color=Color3.fromRGB(187,120,60)}
Items.MysteryCan={Id="MysteryCan",Name="Mystery Can",Machine="CornerStore",Weight=1,Rarity="Global",BaseValue=500000,BaseOneIn=1801111,AssetKey="SodaCan",VisualFamily="Can",CosmeticSlot="Aura",Set="MysterySet",Color=Color3.fromRGB(110,110,125)}
Items.CandyBottle={Id="CandyBottle",Name="Candy Bottle",Machine="SugarRush",Weight=1000000,Rarity="Common",BaseValue=5,BaseOneIn=2,AssetKey="BottleCustom",VisualFamily="Bottle",CosmeticSlot="Shoulder",Set="CandySet",Color=Color3.fromRGB(255,110,187)}
Items.GummyBears={Id="GummyBears",Name="Gummy Bears",Machine="SugarRush",Weight=500000,Rarity="Common",BaseValue=8,BaseOneIn=4,AssetKey="GummyBears",VisualFamily="Bag",CosmeticSlot="Aura",Set="CandySet",Color=Color3.fromRGB(255,77,123)}
Items.CandyBar={Id="CandyBar",Name="Candy Bar",Machine="SugarRush",Weight=200000,Rarity="Uncommon",BaseValue=15,BaseOneIn=9,AssetKey="Chocolate",VisualFamily="Bar",CosmeticSlot="Head",Set="CandySet",Color=Color3.fromRGB(230,91,159)}
Items.Lollipop={Id="Lollipop",Name="Lollipop",Machine="SugarRush",Weight=75000,Rarity="Rare",BaseValue=35,BaseOneIn=24,AssetKey="Lollipop",VisualFamily="Lollipop",CosmeticSlot="Back",Set="CandySet",Color=Color3.fromRGB(255,111,211)}
Items.CottonCandy={Id="CottonCandy",Name="Cotton Candy",Machine="SugarRush",Weight=20000,Rarity="Epic",BaseValue=90,BaseOneIn=90,AssetKey="CandyPack",VisualFamily="Ball",CosmeticSlot="Aura",Set="CandySet",Color=Color3.fromRGB(247,166,255)}
Items.BubbleGum={Id="BubbleGum",Name="Bubble Gum",Machine="SugarRush",Weight=5000,Rarity="Legendary",BaseValue=250,BaseOneIn=360,AssetKey="BubbleGumProp",VisualFamily="Ball",CosmeticSlot="Trail",Set="CandySet",Color=Color3.fromRGB(255,116,187)}
Items.JellyBeans={Id="JellyBeans",Name="Jelly Beans",Machine="SugarRush",Weight=1000,Rarity="Mythic",BaseValue=800,BaseOneIn=1801,AssetKey="CandyPack",VisualFamily="Capsule",CosmeticSlot="Shoulder",Set="CandySet",Color=Color3.fromRGB(129,229,255)}
Items.SourCandy={Id="SourCandy",Name="Sour Candy",Machine="SugarRush",Weight=100,Rarity="Divine",BaseValue=5000,BaseOneIn=18011,AssetKey="CandyPack",VisualFamily="Box",CosmeticSlot="Trail",Set="CandySet",Color=Color3.fromRGB(113,255,122)}
Items.CandyCrownCapsule={Id="CandyCrownCapsule",Name="Candy Crown Capsule",Machine="SugarRush",Weight=10,Rarity="Secret",BaseValue=50000,BaseOneIn=180111,AssetKey="CrownProp",VisualFamily="Capsule",CosmeticSlot="Head",Set="RoyalSet",Color=Color3.fromRGB(255,215,97)}
Items.SecretSugarCube={Id="SecretSugarCube",Name="Secret Sugar Cube",Machine="SugarRush",Weight=1,Rarity="Global",BaseValue=500000,BaseOneIn=1801111,AssetKey="CandyPack",VisualFamily="Cube",CosmeticSlot="Aura",Set="MysterySet",Color=Color3.fromRGB(255,245,252)}
Items.PowerDrink={Id="PowerDrink",Name="Power Drink",Machine="Energy",Weight=1000000,Rarity="Common",BaseValue=5,BaseOneIn=2,AssetKey="SodaCan",VisualFamily="Can",CosmeticSlot="Shoulder",Set="EnergySet",Color=Color3.fromRGB(90,217,255)}
Items.LightningDrink={Id="LightningDrink",Name="Lightning Drink",Machine="Energy",Weight=500000,Rarity="Common",BaseValue=8,BaseOneIn=4,AssetKey="DrinkBottle",VisualFamily="Bottle",CosmeticSlot="Trail",Set="EnergySet",Color=Color3.fromRGB(255,237,65)}
Items.TurboCan={Id="TurboCan",Name="Turbo Can",Machine="Energy",Weight=200000,Rarity="Uncommon",BaseValue=15,BaseOneIn=9,AssetKey="SodaCanMesh",VisualFamily="Can",CosmeticSlot="Head",Set="EnergySet",Color=Color3.fromRGB(255,87,87)}
Items.HyperSoda={Id="HyperSoda",Name="Hyper Soda",Machine="Energy",Weight=75000,Rarity="Rare",BaseValue=35,BaseOneIn=24,AssetKey="BloxyColaProp",VisualFamily="Can",CosmeticSlot="Aura",Set="EnergySet",Color=Color3.fromRGB(208,72,255)}
Items.SportsBottle={Id="SportsBottle",Name="Sports Bottle",Machine="Energy",Weight=20000,Rarity="Epic",BaseValue=90,BaseOneIn=90,AssetKey="WaterBottle",VisualFamily="Bottle",CosmeticSlot="Back",Set="EnergySet",Color=Color3.fromRGB(84,237,184)}
Items.NeonDrink={Id="NeonDrink",Name="Neon Drink",Machine="Energy",Weight=5000,Rarity="Legendary",BaseValue=250,BaseOneIn=360,AssetKey="Bottle",VisualFamily="Bottle",CosmeticSlot="Aura",Set="EnergySet",Color=Color3.fromRGB(57,255,120)}
Items.ShockCan={Id="ShockCan",Name="Shock Can",Machine="Energy",Weight=1000,Rarity="Mythic",BaseValue=800,BaseOneIn=1801,AssetKey="SodaCan",VisualFamily="Can",CosmeticSlot="Trail",Set="EnergySet",Color=Color3.fromRGB(75,164,255)}
Items.AtomicEnergy={Id="AtomicEnergy",Name="Atomic Energy",Machine="Energy",Weight=100,Rarity="Divine",BaseValue=5000,BaseOneIn=18011,AssetKey="SodaCan",VisualFamily="Can",CosmeticSlot="Aura",Set="EnergySet",Color=Color3.fromRGB(145,255,61)}
Items.ReactorCan={Id="ReactorCan",Name="Reactor Can",Machine="Energy",Weight=10,Rarity="Secret",BaseValue=50000,BaseOneIn=180111,AssetKey="SodaCanMesh",VisualFamily="Can",CosmeticSlot="Back",Set="EnergySet",Color=Color3.fromRGB(66,255,186)}
Items.ForbiddenEnergy={Id="ForbiddenEnergy",Name="Forbidden Energy",Machine="Energy",Weight=1,Rarity="Global",BaseValue=500000,BaseOneIn=1801111,AssetKey="SodaCan",VisualFamily="Can",CosmeticSlot="Aura",Set="MysterySet",Color=Color3.fromRGB(34,34,45)}
Items.RubberDuck={Id="RubberDuck",Name="Rubber Duck",Machine="ToyCapsule",Weight=1000000,Rarity="Common",BaseValue=5,BaseOneIn=2,AssetKey="RubberDuck",VisualFamily="Duck",CosmeticSlot="Shoulder",Set="ToySet",Color=Color3.fromRGB(255,223,60)}
Items.TinyRobot={Id="TinyRobot",Name="Tiny Robot",Machine="ToyCapsule",Weight=500000,Rarity="Common",BaseValue=8,BaseOneIn=4,AssetKey="TinyRobot",VisualFamily="Robot",CosmeticSlot="Shoulder",Set="ToySet",Color=Color3.fromRGB(156,165,188)}
Items.PlushRabbit={Id="PlushRabbit",Name="Plush Rabbit",Machine="ToyCapsule",Weight=200000,Rarity="Uncommon",BaseValue=15,BaseOneIn=9,AssetKey="BunnyPlush",VisualFamily="Plush",CosmeticSlot="Shoulder",Set="ToySet",Color=Color3.fromRGB(245,217,230)}
Items.Slime={Id="Slime",Name="Slime",Machine="ToyCapsule",Weight=75000,Rarity="Rare",BaseValue=35,BaseOneIn=24,AssetKey="SlimeBlob",VisualFamily="Ball",CosmeticSlot="Aura",Set="ToySet",Color=Color3.fromRGB(87,255,123)}
Items.Dice={Id="Dice",Name="Dice",Machine="ToyCapsule",Weight=20000,Rarity="Epic",BaseValue=90,BaseOneIn=90,AssetKey="DiceProp",VisualFamily="Cube",CosmeticSlot="Head",Set="ToySet",Color=Color3.fromRGB(244,244,244)}
Items.MiniUFO={Id="MiniUFO",Name="Mini UFO",Machine="ToyCapsule",Weight=5000,Rarity="Legendary",BaseValue=250,BaseOneIn=360,AssetKey="RobotToyAlt",VisualFamily="UFO",CosmeticSlot="Back",Set="ToySet",Color=Color3.fromRGB(145,199,255)}
Items.CrownCapsule={Id="CrownCapsule",Name="Crown Capsule",Machine="ToyCapsule",Weight=1000,Rarity="Mythic",BaseValue=800,BaseOneIn=1801,AssetKey="CrownProp",VisualFamily="Capsule",CosmeticSlot="Head",Set="RoyalSet",Color=Color3.fromRGB(255,216,74)}
Items.MysteryCreature={Id="MysteryCreature",Name="Mystery Creature",Machine="ToyCapsule",Weight=100,Rarity="Divine",BaseValue=5000,BaseOneIn=18011,AssetKey="RobotToy",VisualFamily="Robot",CosmeticSlot="Shoulder",Set="ToySet",Color=Color3.fromRGB(211,111,255)}
Items.GoldenToy={Id="GoldenToy",Name="Golden Toy",Machine="ToyCapsule",Weight=10,Rarity="Secret",BaseValue=50000,BaseOneIn=180111,AssetKey="RobotToyAlt",VisualFamily="Robot",CosmeticSlot="Back",Set="RoyalSet",Color=Color3.fromRGB(255,195,62)}
Items.UnknownCapsule={Id="UnknownCapsule",Name="Unknown Capsule",Machine="ToyCapsule",Weight=1,Rarity="Global",BaseValue=500000,BaseOneIn=1801111,AssetKey="GachaMachinePack",VisualFamily="Capsule",CosmeticSlot="Aura",Set="MysterySet",Color=Color3.fromRGB(61,50,83)}
Items.LuxuryWater={Id="LuxuryWater",Name="Luxury Water",Machine="Luxury",Weight=1000000,Rarity="Common",BaseValue=5,BaseOneIn=2,AssetKey="BottleCustom",VisualFamily="Bottle",CosmeticSlot="Shoulder",Set="RoyalSet",Color=Color3.fromRGB(202,240,255)}
Items.DiamondSoda={Id="DiamondSoda",Name="Diamond Soda",Machine="Luxury",Weight=500000,Rarity="Common",BaseValue=8,BaseOneIn=4,AssetKey="SodaCan",VisualFamily="Can",CosmeticSlot="Aura",Set="RoyalSet",Color=Color3.fromRGB(117,232,255)}
Items.GoldenChocolate={Id="GoldenChocolate",Name="Golden Chocolate",Machine="Luxury",Weight=200000,Rarity="Uncommon",BaseValue=15,BaseOneIn=9,AssetKey="Chocolate",VisualFamily="Bar",CosmeticSlot="Head",Set="RoyalSet",Color=Color3.fromRGB(255,202,68)}
Items.CrownCan={Id="CrownCan",Name="Crown Can",Machine="Luxury",Weight=75000,Rarity="Rare",BaseValue=35,BaseOneIn=24,AssetKey="CrownProp",VisualFamily="Can",CosmeticSlot="Head",Set="RoyalSet",Color=Color3.fromRGB(255,213,89)}
Items.CrystalBottle={Id="CrystalBottle",Name="Crystal Bottle",Machine="Luxury",Weight=20000,Rarity="Epic",BaseValue=90,BaseOneIn=90,AssetKey="BottleCustom",VisualFamily="Bottle",CosmeticSlot="Back",Set="RoyalSet",Color=Color3.fromRGB(157,240,255)}
Items.RoyalCandy={Id="RoyalCandy",Name="Royal Candy",Machine="Luxury",Weight=5000,Rarity="Legendary",BaseValue=250,BaseOneIn=360,AssetKey="CandyPack",VisualFamily="Box",CosmeticSlot="Shoulder",Set="RoyalSet",Color=Color3.fromRGB(189,101,255)}
Items.PlatinumSnack={Id="PlatinumSnack",Name="Platinum Snack",Machine="Luxury",Weight=1000,Rarity="Mythic",BaseValue=800,BaseOneIn=1801,AssetKey="ChipsPack",VisualFamily="Bag",CosmeticSlot="Back",Set="RoyalSet",Color=Color3.fromRGB(211,218,230)}
Items.EmperorCapsule={Id="EmperorCapsule",Name="Emperor Capsule",Machine="Luxury",Weight=100,Rarity="Divine",BaseValue=5000,BaseOneIn=18011,AssetKey="CrownProp",VisualFamily="Capsule",CosmeticSlot="Head",Set="RoyalSet",Color=Color3.fromRGB(255,174,64)}
Items.CelestialDrink={Id="CelestialDrink",Name="Celestial Drink",Machine="Luxury",Weight=10,Rarity="Secret",BaseValue=50000,BaseOneIn=180111,AssetKey="Bottle",VisualFamily="Bottle",CosmeticSlot="Aura",Set="CelestialSet",Color=Color3.fromRGB(255,247,185)}
Items.MillionaireCan={Id="MillionaireCan",Name="Millionaire Can",Machine="Luxury",Weight=1,Rarity="Global",BaseValue=500000,BaseOneIn=1801111,AssetKey="SodaCan",VisualFamily="Can",CosmeticSlot="Aura",Set="RoyalSet",Color=Color3.fromRGB(54,204,115)}
Items.ErrorCan={Id="ErrorCan",Name="Error Can",Machine="Unknown",Weight=1000000,Rarity="Common",BaseValue=5,BaseOneIn=2,AssetKey="SodaCan",VisualFamily="Can",CosmeticSlot="Aura",Set="GlitchSet",Color=Color3.fromRGB(255,65,91)}
Items.MissingTextureSnack={Id="MissingTextureSnack",Name="Missing Texture Snack",Machine="Unknown",Weight=500000,Rarity="Common",BaseValue=8,BaseOneIn=4,AssetKey="ChipsPack",VisualFamily="Bag",CosmeticSlot="Back",Set="GlitchSet",Color=Color3.fromRGB(255,0,255)}
Items.StaticBottle={Id="StaticBottle",Name="Static Bottle",Machine="Unknown",Weight=200000,Rarity="Uncommon",BaseValue=15,BaseOneIn=9,AssetKey="Bottle",VisualFamily="Bottle",CosmeticSlot="Trail",Set="GlitchSet",Color=Color3.fromRGB(180,180,190)}
Items.BlackCan={Id="BlackCan",Name="Black Can",Machine="Unknown",Weight=75000,Rarity="Rare",BaseValue=35,BaseOneIn=24,AssetKey="SodaCanMesh",VisualFamily="Can",CosmeticSlot="Aura",Set="VoidSet",Color=Color3.fromRGB(10,10,14)}
Items.NullCapsule={Id="NullCapsule",Name="Null Capsule",Machine="Unknown",Weight=20000,Rarity="Epic",BaseValue=90,BaseOneIn=90,AssetKey="GachaMachinePack",VisualFamily="Capsule",CosmeticSlot="Head",Set="GlitchSet",Color=Color3.fromRGB(20,20,28)}
Items.CorruptedCola={Id="CorruptedCola",Name="Corrupted Cola",Machine="Unknown",Weight=5000,Rarity="Legendary",BaseValue=250,BaseOneIn=360,AssetKey="BloxyColaMesh",VisualFamily="Can",CosmeticSlot="Shoulder",Set="GlitchSet",Color=Color3.fromRGB(112,39,199)}
Items.UnknownObject={Id="UnknownObject",Name="Unknown Object",Machine="Unknown",Weight=1000,Rarity="Mythic",BaseValue=800,BaseOneIn=1801,AssetKey="StoreItemsPack",VisualFamily="Cube",CosmeticSlot="Back",Set="GlitchSet",Color=Color3.fromRGB(72,50,105)}
Items.VoidContainer={Id="VoidContainer",Name="Void Container",Machine="Unknown",Weight=100,Rarity="Divine",BaseValue=5000,BaseOneIn=18011,AssetKey="BottleCustom",VisualFamily="Bottle",CosmeticSlot="Aura",Set="VoidSet",Color=Color3.fromRGB(37,9,71)}
Items.HeavenlyCan={Id="HeavenlyCan",Name="Heavenly Can",Machine="Unknown",Weight=10,Rarity="Secret",BaseValue=50000,BaseOneIn=180111,AssetKey="SodaCan",VisualFamily="Can",CosmeticSlot="Aura",Set="CelestialSet",Color=Color3.fromRGB(255,247,188)}
Items.QuestionMark={Id="QuestionMark",Name="???",Machine="Unknown",Weight=1,Rarity="Global",BaseValue=500000,BaseOneIn=1801111,AssetKey="QuestionMarkProp",VisualFamily="Capsule",CosmeticSlot="Aura",Set="MysterySet",Color=Color3.fromRGB(255,255,255)}
local drinkShapes={Can=true,Bottle=true};local snackShapes={Bag=true,Bar=true,Lollipop=true,Box=true};local toyShapes={Ball=true,Capsule=true,Robot=true,UFO=true,Duck=true,Plush=true}
local machineValueMultiplier={CornerStore=1,SugarRush=5,Energy=25,ToyCapsule=120,Luxury=600,Unknown=3000}
Items.ByMachine={}
for _,item in pairs(Items) do if type(item)=="table" and item.Id then item.BaseValue=math.max(1,math.floor(item.BaseValue*(machineValueMultiplier[item.Machine] or 1)));if drinkShapes[item.VisualFamily] then item.Category="Drinks" elseif snackShapes[item.VisualFamily] then item.Category="Snacks" elseif toyShapes[item.VisualFamily] then item.Category="Toys" else item.Category="Curios" end;Items.ByMachine[item.Machine]=Items.ByMachine[item.Machine] or {};table.insert(Items.ByMachine[item.Machine],item) end end
for _,list in pairs(Items.ByMachine) do table.sort(list,function(a,b)return a.Weight>b.Weight end) end
return Items
